#!/bin/bash

BRANCHES=`git branch | grep -v "main$" | tr -d "\*"`
MAIN=`git rev-parse main`
for branch in $BRANCHES; do
	if [ -z "`git diff $branch main --name-only 2>&1`" ]; then
		echo $branch
	fi
done