#!/bin/bash

if [ "$2" ]; then
  mkbranch $2 || exit
else
  if [ `branch` == "master" ]; then
    echo "Cannot perform on master"
    exit
  fi

  if [ `git rev-parse HEAD` != `git rev-parse master` ]; then
    echo "current branch must be identical to master; changes will be overridden"
    exit
  fi
fi

MERGE_BASE=$(git merge-base $1 master)
(git diff -p $MERGE_BASE $1 | git apply) && git commit -a -m "Flattened branch $1"
