#!/bin/bash

if [ -f ~/binlocal/$1 ]; then
	echo "hardalias already exists!"
	exit 1
fi

echo "#!/bin/bash" > ~/binlocal-internal/$1
echo $2 \"\$@\" >> ~/binlocal-internal/$1
chmod +x ~/binlocal-internal/$1
