#!/bin/bash

BRANCHES=`git branch | grep -v "main$" | tr -d "\*"`
for branch in $BRANCHES; do
	if [ -z "`git config --get-regexp "branch\.$branch\.remote"`" ]; then
		continue
	fi

	if [ -z "`git ls-remote --heads origin $branch`" ]; then
		echo $branch
	fi	
done