#!/bin/bash

PROGRAM=`which $1`

if [ -z "$PROGRAM" ]; then
	echo "No such script"
	exit 1
fi

if [ -z "$(echo $PROGRAM | grep $HOME/binlocal)" ]; then
	echo "Script not in binlocal"
	exit 1
fi

if [ "$(ls ~/binlocal-public/$(basename $PROGRAM) 2>/dev/null)" ]; then
	echo "Script already in binlocal-public"
	exit 1
fi

cat $PROGRAM

echo
echo -n "Are you sure? (y/n) "
read SURE

if [ "$SURE" != "y" ]; then
	echo "Aborting."
	exit 0
fi

mv `which $1` ~/binlocal-public