#!/usr/bin/env python
import sys
import os

module_path = sys.argv[1]
new_module_path = module_path.replace(".py", "").replace("/", ".")

pyargs =  ["-m", new_module_path] + sys.argv[2:]

import subprocess
subprocess.run(["python"] + pyargs)