#!/bin/bash

# The CU script in ruby is a pain to run remotely and nothing in it is relevant
# Probably deprecate?
#~/binlocal-public/cu --fast

BRANCH=$(branch)
if [ $BRANCH = "main" ]; then
    echo "Do not upload on main"
    exit 1
fi

git push --set-upstream origin $(branch) "$@"